name: bcc
version: 0.2.0-2016-11-10-082866de264
summary: BPF Compiler Collection (BCC)
description: A toolkit for creating efficient kernel tracing and manipulation programs
confinement: strict
grade: stable
plugs:
    mount-observe: null
    system-observe: null
    system-trace: null
apps:
    argdist:
        command: wrapper argdist
    bashreadline:
        command: wrapper bashreadline
    biolatency:
        command: wrapper biolatency
    biosnoop:
        command: wrapper biosnoop
    biotop:
        command: wrapper biotop
    bitesize:
        command: wrapper bitesize
    btrfsdist:
        command: wrapper btrfsdist
    btrfsslower:
        command: wrapper btrfsslower
    cachestat:
        command: wrapper cachestat
    cachetop:
        command: wrapper cachetop
    cpudist:
        command: wrapper cpudist
    dcsnoop:
        command: wrapper dcsnoop
    dcstat:
        command: wrapper dcstat
    execsnoop:
        command: wrapper execsnoop
    ext4dist:
        command: wrapper ext4dist
    ext4slower:
        command: wrapper ext4slower
    filelife:
        command: wrapper filelife
    fileslower:
        command: wrapper fileslower
    filetop:
        command: wrapper filetop
    funccount:
        command: wrapper funccount
    funclatency:
        command: wrapper funclatency
    gethostlatency:
        command: wrapper gethostlatency
    hardirqs:
        command: wrapper hardirqs
    killsnoop:
        command: wrapper killsnoop
    mdflush:
        command: wrapper mdflush
    memleak:
        command: wrapper memleak
    offcputime:
        command: wrapper offcputime
    offwaketime:
        command: wrapper offwaketime
    oomkill:
        command: wrapper oomkill
    opensnoop:
        command: wrapper opensnoop
    pidpersec:
        command: wrapper pidpersec
    runqlat:
        command: wrapper runqlat
    slabratetop:
        command: wrapper slabratetop
    softirqs:
        command: wrapper softirqs
    sslsniff:
        command: wrapper sslsniff
    stackcount:
        command: wrapper stackcount
    stacksnoop:
        command: wrapper stacksnoop
    statsnoop:
        command: wrapper statsnoop
    syncsnoop:
        command: wrapper syncsnoop
    tcpaccept:
        command: wrapper tcpaccept
    tcpconnect:
        command: wrapper tcpconnect
    tcpconnlat:
        command: wrapper tcpconnlat
    tcplife:
        command: wrapper tcplife
    tcpretrans:
        command: wrapper tcpretrans
    tcptop:
        command: wrapper tcptop
    ttysnoop:
        command: wrapper ttysnop
    trace:
        command: wrapper trace
    vfscount:
        command: wrapper vfscount
    vfsstat:
        command: wrapper vfsstat
    wakeuptime:
        command: wrapper wakeuptime
    xfsdist:
        command: wrapper xfsdist
    xfsslower:
        command: wrapper xfsslower
    zfsdist:
        command: wrapper zfsdist
    zfsslower:
        command: wrapper zfsslower
parts:
    bcc:
        plugin: cmake
        configflags:
            - -DCMAKE_INSTALL_PREFIX=/usr
        source: git://github.com/iovisor/bcc
        build-packages:
            - bison
            - build-essential
            - cmake
            - flex
            - libedit-dev
            - libllvm3.7
            - llvm-3.7-dev
            - libclang-3.7-dev
            - python
            - zlib1g-dev
            - libelf-dev
        stage-packages:
            - python
        snap:
            - usr/bin/python*
            - usr/share/bcc/tools
            - usr/lib/*/lib*.so*
            - usr/lib/python2.7
            - -usr/share/bcc/tools/doc
    wrapper:
        source: .
        plugin: copy
        files:
            wrapper: bin/wrapper

# vim: set ai et sts=4 tabstop=4 sw=4:
