name: bcc
version: 0.1.8
summary: BPF Compiler Collection (BCC)
description: A toolkit for creating efficient kernel tracing and manipulation programs
apps:
    argdist:
        # ubuntu-core-launcher mounts a new instance of devpts and python
        # cannot grab a pty, so run unbuffered (-u).
        #
        # Snappy does not yet support CAP_SYS_ADMIN for unconfined snaps:
        # https://bugs.launchpad.net/snappy/+bug/1586581
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/argdist
    bashreadline:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/bashreadline
    biolatency:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/biolatency
    biosnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/biosnoop
    biotop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/biotop
    bitesize:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/bitesize
    btrfsdist:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/btrfsdist
    btrfsslower:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/btrfsslower
    cachestat:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/cachestat
    dcsnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/dcsnoop
    dcstat:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/dcstat
    execsnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/execsnoop
    ext4dist:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/ext4dist
    ext4slower:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/ext4slower
    filelife:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/filelife
    fileslower:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/fileslower
    filetop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/filetop
    funccount:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/funccount
    funclatency:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/funclatency
    gethostlatency:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/gethostlatency
    hardirqs:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/hardirqs
    killsnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/killsnoop
    mdflush:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/mdflush
    memleak:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/memleak
    offcputime:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/offcputime
    offwaketime:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/offwaketime
    oomkill:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/oomkill
    opensnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/opensnoop
    pidpersec:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/pidpersec
    runqlat:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/runqlat
    softirqs:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/softirqs
    stackcount:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/stackcount
    stacksnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/stacksnoop
    statsnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/statsnoop
    syncsnoop:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/syncsnoop
    tcpaccept:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/tcpaccept
    tcpconnect:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/tcpconnect
    tcpconnlat:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/tcpconnlat
    tcpretrans:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/tcpretrans
    trace:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/trace
    vfscount:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/vfscount
    vfsstat:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/vfsstat
    wakeuptime:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/wakeuptime
    xfsdist:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/xfsdist
    xfsslower:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/xfsslower
    zfsdist:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/zfsdist
    zfsslower:
        command: sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH $SNAP/usr/bin/python -u $SNAP/usr/share/bcc/tools/zfsslower
parts:
    bcc:
        plugin: cmake
        configflags:
            - -DCMAKE_INSTALL_PREFIX=/usr
        source: git://github.com/iovisor/bcc
        source-tag: v0.1.8
        build-packages:
            - bison
            - build-essential
            - cmake
            - flex
            - libedit-dev
            - libllvm3.7
            - llvm-3.7-dev
            - libclang-3.7-dev
            - python
            - zlib1g-dev
        stage-packages:
            - python
        filesets:
            all:
                - usr/bin/python*
                - usr/share/bcc/tools
                - usr/lib/*/lib*.so*
                - usr/lib/python2.7
        stage:
            - $all
        snap:
            - $all

# vim: set ai et sts=4 tabstop=4 sw=4:
