name: bcc
version: 0.1.8
summary: BPF Compiler Collection (BCC)
description: A toolkit for creating efficient kernel tracing and manipulation programs
confinement: devmode
apps:
    argdist:
        # ubuntu-core-launcher mounts a new instance of devpts and python
        # cannot grab a pty, so run unbuffered (-u).
        #
        # Snappy does not yet support CAP_SYS_ADMIN for unconfined snaps:
        # https://bugs.launchpad.net/snappy/+bug/1586581
        command: wrapper argdist
    bashreadline:
        command: wrapper bashreadline
    biolatency:
        command: wrapper biolatency
    biosnoop:
        command: wrapper biosnoop
    biotop:
        command: wrapper biotop
    bitesize:
        command: wrapper bitesize
    btrfsdist:
        command: wrapper btrfsdist
    btrfsslower:
        command: wrapper btrfsslower
    cachestat:
        command: wrapper cachestat
    dcsnoop:
        command: wrapper dcsnoop
    dcstat:
        command: wrapper dcstat
    execsnoop:
        command: wrapper execsnoop
    ext4dist:
        command: wrapper ext4dist
    ext4slower:
        command: wrapper ext4slower
    filelife:
        command: wrapper filelife
    fileslower:
        command: wrapper fileslower
    filetop:
        command: wrapper filetop
    funccount:
        command: wrapper funccount
    funclatency:
        command: wrapper funclatency
    gethostlatency:
        command: wrapper gethostlatency
    hardirqs:
        command: wrapper hardirqs
    killsnoop:
        command: wrapper killsnoop
    mdflush:
        command: wrapper mdflush
    memleak:
        command: wrapper memleak
    offcputime:
        command: wrapper offcputime
    offwaketime:
        command: wrapper offwaketime
    oomkill:
        command: wrapper oomkill
    opensnoop:
        command: wrapper opensnoop
    pidpersec:
        command: wrapper pidpersec
    runqlat:
        command: wrapper runqlat
    softirqs:
        command: wrapper softirqs
    stackcount:
        command: wrapper stackcount
    stacksnoop:
        command: wrapper stacksnoop
    statsnoop:
        command: wrapper statsnoop
    syncsnoop:
        command: wrapper syncsnoop
    tcpaccept:
        command: wrapper tcpaccept
    tcpconnect:
        command: wrapper tcpconnect
    tcpconnlat:
        command: wrapper tcpconnlat
    tcpretrans:
        command: wrapper tcpretrans
    trace:
        command: wrapper trace
    vfscount:
        command: wrapper vfscount
    vfsstat:
        command: wrapper vfsstat
    wakeuptime:
        command: wrapper wakeuptime
    xfsdist:
        command: wrapper xfsdist
    xfsslower:
        command: wrapper xfsslower
    zfsdist:
        command: wrapper zfsdist
    zfsslower:
        command: wrapper zfsslower
parts:
    bcc:
        plugin: cmake
        configflags:
            - -DCMAKE_INSTALL_PREFIX=/usr
        source: git://github.com/iovisor/bcc
        source-tag: v0.1.8
        build-packages:
            - bison
            - build-essential
            - cmake
            - flex
            - libedit-dev
            - libllvm3.7
            - llvm-3.7-dev
            - libclang-3.7-dev
            - python
            - zlib1g-dev
        stage-packages:
            - python
        snap:
            - usr/bin/python*
            - usr/share/bcc/tools
            - usr/lib/*/lib*.so*
            - usr/lib/python2.7
            - -usr/share/bcc/tools/doc
    glue:
        plugin: copy
        files:
            wrapper: bin/wrapper

# vim: set ai et sts=4 tabstop=4 sw=4:
